terraform-apply:
	terraform init
	terraform apply -auto-approve -var-file=tf-env-vars/main.tfvars

terraform-destroy:
	terraform init
	terraform destroy -auto-approve -var-file=tf-env-vars/main.tfvars